# Data Augmentation

Simple data augmentation methods for Dots and Boxes training data.

In [1]:
import numpy as np

In [2]:
raw_data = np.load("StageFour-AlphaZeroV7-128-7x6-18:36-24_05_2018.npz")

In [3]:
input_data = raw_data['input']
policy_data = raw_data['policy']
value_data = raw_data['value']

print(input_data.shape)
print(policy_data.shape)
print(value_data.shape)

(128, 15, 17)
(128, 15, 17)
(128, 1)


In [4]:
example_idx = np.random.randint(input_data.shape[0])
print("input:")
print(input_data[example_idx])
print("policy:")
print(policy_data[example_idx])
print("value:")
print(value_data[example_idx])

input:
[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0 215   0 215   0 215   0 215 255 215   0 215 255 215   0 215   0]
 [  0   0   0 255   0   0   0   0   0 255   0   0   0   0   0   0   0]
 [  0 215 255 215   0 215 255 215   0 215   0 215   0 215 255 215   0]
 [  0   0   0 255   0   0   0 255   0   0   0 255   0   0   0   0   0]
 [  0 215   0 215 255 215   0 215 255 215 255 215 255 215 255 215   0]
 [  0 255   0 255   0   0   0   0   0   0   0   0   0 255   0   0   0]
 [  0 215   0 215   0 215   0 215   0 215   0 215   0 215   0 215   0]
 [  0   0   0   0   0   0   0 255   0   0   0 255   0   0   0 255   0]
 [  0 215   0 215   0 215   0 215   0 215   0 215   0 215   0 215   0]
 [  0   0   0   0   0   0   0   0   0   0   0 255   0   0   0   0   0]
 [  0 215 255 215   0 215   0 215 255 215   0 215   0 215   0 215   0]
 [  0   0   0   0   0 255   0   0   0 255   0   0   0   0   0   0   0]
 [  0 215 255 215 255 215   0 215   0 215   0 215   0 215   0 215   0]

In [11]:
print(np.flip(input_data[example_idx], 0))
print(np.flip(policy_data[example_idx], 0))

[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0 215 255 215 255 215   0 215   0 215   0 215   0 215   0 215   0]
 [  0   0   0   0   0 255   0   0   0 255   0   0   0   0   0   0   0]
 [  0 215 255 215   0 215   0 215 255 215   0 215   0 215   0 215   0]
 [  0   0   0   0   0   0   0   0   0   0   0 255   0   0   0   0   0]
 [  0 215   0 215   0 215   0 215   0 215   0 215   0 215   0 215   0]
 [  0   0   0   0   0   0   0 255   0   0   0 255   0   0   0 255   0]
 [  0 215   0 215   0 215   0 215   0 215   0 215   0 215   0 215   0]
 [  0 255   0 255   0   0   0   0   0   0   0   0   0 255   0   0   0]
 [  0 215   0 215 255 215   0 215 255 215 255 215 255 215 255 215   0]
 [  0   0   0 255   0   0   0 255   0   0   0 255   0   0   0   0   0]
 [  0 215 255 215   0 215 255 215   0 215   0 215   0 215 255 215   0]
 [  0   0   0 255   0   0   0   0   0 255   0   0   0   0   0   0   0]
 [  0 215   0 215   0 215   0 215 255 215   0 215 255 215   0 215   0]
 [  0 

In [12]:
print(np.flip(input_data[example_idx], 1))
print(np.flip(policy_data[example_idx], 1))

[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0 215   0 215 255 215   0 215 255 215   0 215   0 215   0 215   0]
 [  0   0   0   0   0   0   0 255   0   0   0   0   0 255   0   0   0]
 [  0 215 255 215   0 215   0 215   0 215 255 215   0 215 255 215   0]
 [  0   0   0   0   0 255   0   0   0 255   0   0   0 255   0   0   0]
 [  0 215 255 215 255 215 255 215 255 215   0 215 255 215   0 215   0]
 [  0   0   0 255   0   0   0   0   0   0   0   0   0 255   0 255   0]
 [  0 215   0 215   0 215   0 215   0 215   0 215   0 215   0 215   0]
 [  0 255   0   0   0 255   0   0   0 255   0   0   0   0   0   0   0]
 [  0 215   0 215   0 215   0 215   0 215   0 215   0 215   0 215   0]
 [  0   0   0   0   0 255   0   0   0   0   0   0   0   0   0   0   0]
 [  0 215   0 215   0 215   0 215 255 215   0 215   0 215 255 215   0]
 [  0   0   0   0   0   0   0 255   0   0   0 255   0   0   0   0   0]
 [  0 215   0 215   0 215   0 215   0 215   0 215 255 215 255 215   0]
 [  0 

In [17]:
print(policy_data[0:2])
print(np.flip(policy_data[0:2], -1))
print(np.flip(policy_data[0:2], -2))

[[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
  [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
  [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
  [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
  [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
  [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
  [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
  [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
  [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
  [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
  [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
  [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
  [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
  [  0   0   0   0   0   0   0   0   0   0 255   0   0   0   0  

In [33]:
def augment_data(input_data, policy_data):
    assert(len(input_data.shape) == 3)
    assert(len(policy_data.shape) == 3)
    assert(input_data.shape[0] == policy_data.shape[0])
    input_ret = np.zeros(input_data.shape, dtype=input_data.dtype)
    policy_ret = np.zeros(policy_data.shape, dtype=policy_data.dtype)
    for i in range(input_data.shape[0]):
        op = np.random.randint(5)
        if op == 0:
            input_ret[i] = input_data[i]
            policy_ret[i] = policy_data[i]
        if op == 1:
            input_ret[i] = np.flip(input_data[i], -1)
            policy_ret[i] = np.flip(policy_data[i], -1)
        if op == 2:
            input_ret[i] = np.flip(input_data[i], -2)
            policy_ret[i] = np.flip(policy_data[i], -2)
        if op == 3:
            input_ret[i] = np.flip(np.flip(input_data[i], -1), -2)
            policy_ret[i] = np.flip(np.flip(policy_data[i], -1), -2)
        if op == 4:
            input_ret[i] = np.flip(np.flip(input_data[i], -2), -1)
            policy_ret[i] = np.flip(np.flip(policy_data[i], -2), -1)
    return input_ret, policy_ret

In [34]:
dati = input_data[0:2]
datp = policy_data[0:2]
adati, adatp = augment_data(dati, datp)
print(dati.shape)
print(datp.shape)
print(adati.shape)
print(adatp.shape)
print(dati[0])
print(datp[0])
print(adati[0])
print(adatp[0])

(2, 15, 17)
(2, 15, 17)
(2, 15, 17)
(2, 15, 17)
[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0 215   0 215 255 215 255 215 255 215 255 215   0 215 255 215   0]
 [  0 255   0 255 150 255  65 255  65 255   0   0   0 255  65 255   0]
 [  0 215   0 215 255 215 255 215 255 215   0 215 255 215 255 215   0]
 [  0 255   0 255 150 255  65 255  65 255   0 255   0   0   0 255   0]
 [  0 215   0 215 255 215 255 215 255 215   0 215   0 215   0 215   0]
 [  0 255   0 255 150 255  65 255  65 255   0 255   0 255   0   0   0]
 [  0 215   0 215 255 215 255 215 255 215   0 215   0 215 255 215   0]
 [  0 255   0 255   0   0   0   0   0   0   0 255   0   0   0   0   0]
 [  0 215   0 215   0 215 255 215 255 215 255 215 255 215 255 215   0]
 [  0   0   0 255   0   0   0 255   0   0   0   0   0   0   0   0   0]
 [  0 215 255 215 255 215   0 215   0 215 255 215 255 215 255 215   0]
 [  0 255  65 255  65 255   0 255   0   0   0 255 150 255 150 255   0]
 [  0 215 255 215 255 215   0